### ISSUE TITLE
making navbar pretty

### ISSUE THREAD

**Issue by sagarb2003** [roannav/matrix-movies-website-hacktoberfest#116]

**Comment by sagarb2003** [comment]
Assign me this issue i will make navbar more beautiful and add label of hacktoberfest

**Comment by roannav** [comment]
Hi @sagarb2003, another person  improved the hovering style of the navbar, just 30 minutes ago.  Would you be willing to work on the responsiveness of the navbar, so that it looks good on different screen sizes.  For example, for the iPad Air which has 820px width, but the navbar extends too far to the right and left, going outside of the screen).

The navbar looks ok for wide desktops.  It's also ok for mobile, because it collapses to a hamburger menu.  However, for some of these middle width screen sizes,  the navbar could go to 2 rows to make everything fit.

Please let me know if you are interested in this modified issue.   Thanks.

**Comment by sagarb2003** [comment]
ok i will do this assign me

**Comment by roannav** [comment]
@sagarb2003 Thank you very much for all of your help!
