### ISSUE TITLE
 change the overall folder structure of the project for easy maintenance and Also deploy it to GitHub pages

### ISSUE THREAD

**Issue by ezhillragesh** [roannav/matrix-movies-website-hacktoberfest#36]

**Comment by ezhillragesh** [comment]
I would Like to work on the issue if you want to change the structure

**Comment by roannav** [comment]
Hi @ezhillragesh,  the website is already live at GitHub pages: [Matrix Movies Website](https://roannav.github.io/matrix-movies-website-hacktoberfest/).

How would you change the folder structure?

**Comment by ezhillragesh** [comment]
I am Planning something like this :
/src              # Source code files
    /js           # JavaScript files
    /css          # CSS files
/assets           #  images, videos
/docs             # documentation
/public           # (html file)
/config           # configuration files  

if you are willing to make a folder restructure like this let me know please.

**Comment by roannav** [comment]
Hi @ezhillragesh,  I don't think we need all those directories for this simple website.  

One thing that's helpful is...
The styles.css could go into a new styles/ folder.  
Then all the .html files will need to be updated with the new location of styles.css

Putting styles.css into a styles/ folder is useful, because styles.css might later be split into several different .css files.

So, if you're interested in doing that, then I'll assign you.

**Comment by ezhillragesh** [comment]
Yes I am interested in doing it , can you assign it to me?

**Comment by roannav** [comment]
@ezhillragesh Thank you!  You're assigned.

**Comment by roannav** [comment]
@ezhillragesh I am going to close this issue.   The reason is that with so many contributions over the last 2 weeks, the styles.css was rapidly getting very disorganized.  I decided I needed to split styles.css into new files under css/, so that this project would remain easy to understand. So this task is done.

**Comment by roannav** [comment]
Thank you for contributing the ideas you wrote about in this issue!

@all-contributors please add @ezhillragesh  for ideas
