### ISSUE TITLE
change the css of cast-crew page 

### ISSUE THREAD

**Issue by Deepankar1484** [roannav/matrix-movies-website-hacktoberfest#83]
Hello @roannav, Hope you are doing well. I think i can work on this issue by enhancing the CSS of cast-crew page .

So please assign this issue to me and add the labels for hactober fest.

**Comment by roannav** [comment]
Hi @Deepankar1484,  thanks for creating this issue!  I was just about to do that, but you were faster than me.  😆   You are assigned to work on it.  

#### Here are all the files that could be useful:
cast-crew.html
css/pages/cast-crew.css
js/cast-crew.js

#### These following files probably shouldn't be changed, but contain useful data that could be used in the Cast & Crew page.
js/cast.js  contains an array of all the cast members
js/crew.js contains an array of all the crew members

***
Styles that are for the Cast & Crew page should go into css/pages/cast-crew.css. They will override anything in css/default.css.

Please add style to ONLY the content inside of `<section class="cast-section">` or `<section class="crew-section">`

Please do NOT change the other parts of the page, like the header, navbar, or footer, since I want that consistent between all the pages.

**Comment by Wafmulla** [comment]
Can you assign this issue to me under Hacktoberfest label?

**Comment by roannav** [comment]
Thank you @Wafmulla, you've been assigned.  Interested to see what changes you'll make!

**Comment by harshit1142** [comment]
Can you assign this issue to me ?

**Comment by roannav** [comment]
Hi @harshit1142, there are already other people recently assigned to work on both the cast-crew page and the review page.  However, if you find something to improve on another page, please feel free to create a new issue.  Thanks!
